/**
 * Report generation utility for Brand Guardian AI
 * Generates and downloads a structured compliance audit report.
 */

export function generateReportMarkdown(audit) {
  if (!audit) return '';

  const dateStr = new Date(audit.timestamp || Date.now()).toUTCString();
  const violations = audit.compliance_results || [];
  const critical = violations.filter((v) => v.severity === 'CRITICAL');
  const warnings = violations.filter((v) => v.severity === 'WARNING');

  return `# BRAND GUARDIAN AI — VIDEO COMPLIANCE AUDIT REPORT

**Audit Date:** ${dateStr}
**Session ID:** ${audit.session_id || 'N/A'}
**Video ID:** ${audit.video_id || 'N/A'}
**Video URL:** ${audit.video_url || 'N/A'}
**Final Verdict:** ${audit.status || 'UNKNOWN'}
**Compliance Health Score:** ${audit.compliance_score ?? (audit.status === 'PASS' ? 95 : 60)}/100

---

## 1. Executive Summary
${audit.final_report || 'No executive summary provided.'}

---

## 2. Violation Summary
* Total Issues Detected: ${violations.length}
* Critical Violations: ${critical.length}
* Warnings: ${warnings.length}

---

## 3. Compliance Findings & Citations
${
  violations.length === 0
    ? 'No violations found. Content meets regulatory and advertising platform requirements.'
    : violations
        .map(
          (item, idx) => `### Issue ${idx + 1}: [${item.severity}] ${item.category}
- **Timestamp:** ${item.timestamp || 'N/A'}
- **Description:** ${item.description}
${item.rule_reference ? `- **Rule Reference:** ${item.rule_reference}` : ''}
`
        )
        .join('\n')
}

---

## 4. Multimodal Signal Extraction

### Speech-to-Text Audio Transcript
${audit.transcript || 'No spoken audio transcript recorded.'}

### On-Screen Visual OCR Frames
${
  audit.ocr_text && audit.ocr_text.length > 0
    ? audit.ocr_text.map((ocr, i) => `${i + 1}. ${ocr}`).join('\n')
    : 'No on-screen OCR text extracted.'
}

---
*Report generated by Brand Guardian AI Multimodal Auditing Engine*
`;
}

export function downloadReportFile(audit) {
  const markdown = generateReportMarkdown(audit);
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `compliance_audit_${audit.video_id || 'report'}_${Date.now()}.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
